"""billing and credits

Revision ID: 0028_billing_and_credits
Revises: 0027_multitenancy_users
Create Date: 2026-09-14 02:46:44.000000

全テーブル作成を既存ガイド (0011 等) と同じ存在チェックで冪等化する。

注意: このリビジョンは既に適用済みの DB には流儀の影響が及ばないため、
``stripe_webhook_events`` と ``credit_transactions`` のスキーマ是正
（モデル不一致 PK / ``sa.text('now()')`` 既定値）は 0033_schema_reconciliation
で行うこと。
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0028_billing_and_credits'
down_revision = '0027_multitenancy_users'
branch_labels = None
depends_on = None


def _table_exists(table_name: str) -> bool:
    return table_name in sa.inspect(op.get_bind()).get_table_names()


def _index_exists(table_name: str, index_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    if table_name not in inspector.get_table_names():
        return False
    return any(ix['name'] == index_name for ix in inspector.get_indexes(table_name))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists('credit_transactions'):
        op.create_table(
            'credit_transactions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('amount', sa.Integer(), nullable=False),
            sa.Column('balance_after', sa.Integer(), nullable=False),
            sa.Column('transaction_type', sa.String(length=30), nullable=False),
            sa.Column('task_id', sa.String(length=100), nullable=True),
            sa.Column('description', sa.String(length=255), nullable=False),
            # SQLite には now() 関数が無いため sa.text('now()') は
            # 既定値としてそのまま焼き込まれ、以降の全 INSERT が失敗する。
            # sa.func.now() は CURRENT_TIMESTAMP にレンダリングされる。
            sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
    if not _index_exists('credit_transactions', op.f('ix_credit_transactions_user_id')):
        op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    if not _index_exists('credit_transactions', op.f('ix_credit_transactions_task_id')):
        op.create_index(op.f('ix_credit_transactions_task_id'), 'credit_transactions', ['task_id'], unique=False)

    if not _table_exists('subscriptions'):
        op.create_table(
            'subscriptions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('stripe_subscription_id', sa.String(length=255), nullable=False),
            sa.Column('stripe_customer_id', sa.String(length=255), nullable=False),
            sa.Column('plan_tier', sa.String(length=20), nullable=False),
            sa.Column('status', sa.String(length=30), nullable=False),
            sa.Column('current_period_end', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('user_id'),
            sa.UniqueConstraint('stripe_subscription_id')
        )
    if not _index_exists('subscriptions', op.f('ix_subscriptions_stripe_subscription_id')):
        op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)

    if not _table_exists('stripe_webhook_events'):
        op.create_table(
            'stripe_webhook_events',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
            sa.Column('event_type', sa.String(length=50), nullable=False),
            sa.Column('processed', sa.Boolean(), nullable=False, default=False),
            # sa.text('now()') は SQLite で機能しないため sa.func.now()（CURRENT_TIMESTAMP）を使う。
            sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('stripe_event_id')
        )

    # Note: stripe_customer_id column already exists in users table, so we don't need to add it
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _table_exists('stripe_webhook_events'):
        op.drop_table('stripe_webhook_events')
    if _table_exists('subscriptions') and _index_exists('subscriptions', op.f('ix_subscriptions_stripe_subscription_id')):
        op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    if _table_exists('subscriptions'):
        op.drop_table('subscriptions')
    if _table_exists('credit_transactions') and _index_exists('credit_transactions', op.f('ix_credit_transactions_task_id')):
        op.drop_index(op.f('ix_credit_transactions_task_id'), table_name='credit_transactions')
    if _table_exists('credit_transactions') and _index_exists('credit_transactions', op.f('ix_credit_transactions_user_id')):
        op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    if _table_exists('credit_transactions'):
        op.drop_table('credit_transactions')
    # ### end Alembic commands ###
